name: lambda_deployment
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["ecr_docker_deployment"]
    types:
      - completed


jobs:
  deploy_lambda:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: deploy
        run: |
          docker build --platform linux/amd64 -t aws-image:etl_v2 .
          docker tag aws-image:etl_v2 505276000084.dkr.ecr.ca-central-1.amazonaws.com/elt-n2n:latest
          docker push 505276000084.dkr.ecr.ca-central-1.amazonaws.com/elt-n2n:latest

      - name: Update Lambda function
        #uses: aws-actions/aws-lambda-update-function-code@v1
        #with:
        run: |
          function-name: lambda_function.lambda_handler
          image-uri: ImageUri=111122223333.dkr.ecr.us-east-1.amazonaws.com/hello-world:latest